// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UCt5HaW8U8dZDEpe-98mjInq-I-L7E0',
    appId: '1:452815530145:web:89aa579afdcd276a8a28e0',
    messagingSenderId: '452815530145',
    projectId: 'pokemon-3c4b2',
    authDomain: 'pokemon-3c4b2.firebaseapp.com',
    storageBucket: 'pokemon-3c4b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFraM4lNrtjKAJKImW2pP1iuOQjFwNx3o',
    appId: '1:452815530145:android:255fb3958720e55a8a28e0',
    messagingSenderId: '452815530145',
    projectId: 'pokemon-3c4b2',
    storageBucket: 'pokemon-3c4b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAs6GdqbKO22JLB_7Xw0CssGmR9E9yilI',
    appId: '1:452815530145:ios:3a2b72f691c369308a28e0',
    messagingSenderId: '452815530145',
    projectId: 'pokemon-3c4b2',
    storageBucket: 'pokemon-3c4b2.firebasestorage.app',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAs6GdqbKO22JLB_7Xw0CssGmR9E9yilI',
    appId: '1:452815530145:ios:3a2b72f691c369308a28e0',
    messagingSenderId: '452815530145',
    projectId: 'pokemon-3c4b2',
    storageBucket: 'pokemon-3c4b2.firebasestorage.app',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8UCt5HaW8U8dZDEpe-98mjInq-I-L7E0',
    appId: '1:452815530145:web:ad6bc3576725f5308a28e0',
    messagingSenderId: '452815530145',
    projectId: 'pokemon-3c4b2',
    authDomain: 'pokemon-3c4b2.firebaseapp.com',
    storageBucket: 'pokemon-3c4b2.firebasestorage.app',
  );
}
